"""Regression guard: ROI resize must match the training notebook's interpolation.

The training notebook (``video-lbp-top-motion-per-subject-calibration.ipynb`` ==
the handoff's ``refactored_v2``) resizes every ROI with ``cv2.resize(roi, (64, 64))``
— i.e. cv2's **default ``INTER_LINEAR``**. The live extractor briefly forced
``cv2.INTER_AREA`` in ``features._roi_crop``; ``INTER_AREA`` is the textbook-better
downscale filter, but it produces *different* 64x64 pixels, hence different LBP
codes, hence a 90-d LBP-TOP block that lives in a different feature space than the
StandardScaler / RandomForest were fit on.

``test_pipeline_fixtures.py`` only checks the sum-to-9.0 invariant, which BOTH
interpolations satisfy — that is exactly how the ``INTER_AREA`` regression stayed
green. This file pins the *actual per-plane values* against a notebook-derived
reference, so it FAILS if ``INTER_AREA`` (or any non-default resize) is
reintroduced and PASSES only when the resize matches training.

The reference (``NOTEBOOK_LBP_REFERENCE``) was generated by ``_notebook_lbptop``
below — a verbatim port of the notebook's ``extract_roi`` / ``build_roi_video`` /
``lbp_hist`` / ``lbp_top`` cells (resize left at the cv2 default, histograms
``density=True``) — run on the deterministic synthetic clip built here. No
dataset and no MediaPipe are needed: this isolates the one step that diverged
(crop -> resize -> LBP-TOP). To regenerate, run ``_notebook_lbptop`` on
``_synthetic_frames_and_landmarks()`` and replace the constant; only ever
regenerate against the notebook port, never against ``features.py``.
"""

from __future__ import annotations

import cv2
import numpy as np
from skimage.feature import local_binary_pattern

from ml_video import features as F

# --- Deterministic synthetic input -------------------------------------------

_H = _W = 256
_T = 8

# Fixed normalized ROI boxes, comfortably larger than 64x64 so the resize is a
# genuine downscale (where INTER_AREA and INTER_LINEAR diverge most).
_BOXES = {
    "mouth": {"x": (0.18, 0.82), "y": (0.55, 0.88)},
    "left_eye": {"x": (0.15, 0.45), "y": (0.18, 0.42)},
    "right_eye": {"x": (0.55, 0.85), "y": (0.18, 0.42)},
}


def _make_frame(t: int) -> np.ndarray:
    """A BGR frame with high-frequency texture (so the interpolation choice bites)."""
    ys, xs = np.mgrid[0:_H, 0:_W]
    g = (
        128
        + 80 * np.sin((xs + 2 * t) / 3.0)
        + 60 * np.cos((ys - 3 * t) / 4.0)
        + 40 * np.sin((xs + ys) / 2.5)
    )
    g = np.clip(g, 0, 255).astype(np.uint8)
    return np.dstack([g, g, g]).astype(np.uint8)


def _synthetic_frames_and_landmarks() -> tuple[list[np.ndarray], np.ndarray]:
    """Deterministic ``(frames, landmarks)`` driving every ROI to a fixed crop."""
    row = np.full(F.LANDMARK_DIM, 0.5, dtype=np.float64)
    for roi, idxs in F.ROI_LANDMARKS.items():
        bx, by = _BOXES[roi]["x"], _BOXES[roi]["y"]
        row[2 * idxs[0]], row[2 * idxs[0] + 1] = bx[0], by[0]
        row[2 * idxs[1]], row[2 * idxs[1] + 1] = bx[1], by[1]
        for i in idxs[2:]:
            row[2 * i], row[2 * i + 1] = (bx[0] + bx[1]) / 2, (by[0] + by[1]) / 2
    frames = [_make_frame(t) for t in range(_T)]
    landmarks = np.tile(row, (_T, 1))
    return frames, landmarks


# --- Verbatim notebook port (the reference path; resize = cv2 default) --------
#
# Mirrors notebook cells (nb lines ~747-808): extract_roi, build_roi_video,
# lbp_hist (density=True), lbp_top. The ONLY thing this must keep faithful vs
# features.py is the resize interpolation (cv2 default = INTER_LINEAR).


def _nb_lbp_hist(img: np.ndarray) -> np.ndarray:
    lbp = local_binary_pattern(img, F.LBP_P, F.LBP_R, method=F.LBP_METHOD)
    hist, _ = np.histogram(
        lbp.ravel(), bins=np.arange(0, F.LBP_P + 3), range=(0, F.LBP_P + 2), density=True
    )
    return hist


def _nb_lbp_top(video: np.ndarray) -> np.ndarray:
    _t, h, w = video.shape
    xy = [_nb_lbp_hist(video[t]) for t in range(video.shape[0])]
    xt = [_nb_lbp_hist(video[:, y, :]) for y in range(0, h, 2)]
    yt = [_nb_lbp_hist(video[:, :, x]) for x in range(0, w, 2)]
    return np.concatenate(
        [np.mean(xy, axis=0), np.mean(xt, axis=0), np.mean(yt, axis=0)]
    )


def _nb_extract_roi(frame, landmarks2d, idxs, margin=10):
    if np.all(landmarks2d == 0):
        return None
    h, w = frame.shape[:2]
    pts = np.array([landmarks2d[i] for i in idxs], dtype=float).copy()
    pts[:, 0] *= w
    pts[:, 1] *= h
    x_min, y_min = pts.min(axis=0).astype(int)
    x_max, y_max = pts.max(axis=0).astype(int)
    x_min = max(0, x_min - margin)
    y_min = max(0, y_min - margin)
    x_max = min(w, x_max + margin)
    y_max = min(h, y_max + margin)
    if x_max <= x_min or y_max <= y_min:
        return None
    roi = frame[y_min:y_max, x_min:x_max]
    if roi.size == 0:
        return None
    return cv2.cvtColor(roi, cv2.COLOR_BGR2GRAY)


def _nb_build_roi_video(frames, landmarks_seq, roi_indices):
    seq = []
    for frame, landmarks_flat in zip(frames, landmarks_seq, strict=True):
        lm = landmarks_flat.reshape(-1, 2)
        roi = _nb_extract_roi(frame, lm, roi_indices)
        if roi is None:
            continue
        seq.append(cv2.resize(roi, (64, 64)))  # cv2 default = INTER_LINEAR (training)
    return np.array(seq)


def _nb_lbptop(frames, landmarks_seq) -> np.ndarray:
    feats = []
    for roi in ("mouth", "left_eye", "right_eye"):
        v = _nb_build_roi_video(frames, landmarks_seq, F.ROI_LANDMARKS[roi])
        if v.shape[0] == 0:
            continue
        feats.append(_nb_lbp_top(v))
    return np.concatenate(feats)


# --- Notebook-derived golden (committed reference) ----------------------------
# Generated by _nb_lbptop(*_synthetic_frames_and_landmarks()). See module docstring.
NOTEBOOK_LBP_REFERENCE = np.array(
    [
        0.01275634765625, 0.078460693359375, 0.05303955078125, 0.159637451171875,
        0.34527587890625, 0.158111572265625, 0.047393798828125, 0.04766845703125,
        0.044158935546875, 0.053497314453125, 0.03399658203125, 0.102294921875,
        0.12030029296875, 0.155029296875, 0.2607421875, 0.1141357421875,
        0.06121826171875, 0.03643798828125, 0.04766845703125, 0.06817626953125,
        0.0167236328125, 0.09423828125, 0.06707763671875, 0.18255615234375,
        0.35894775390625, 0.1507568359375, 0.0340576171875, 0.01702880859375,
        0.0377197265625, 0.0408935546875, 0.005157470703125, 0.028289794921875,
        0.033935546875, 0.191558837890625, 0.44964599609375, 0.19061279296875,
        0.025909423828125, 0.013153076171875, 0.037933349609375, 0.0238037109375,
        0.01751708984375, 0.0933837890625, 0.08551025390625, 0.16461181640625,
        0.37652587890625, 0.1190185546875, 0.04327392578125, 0.0196533203125,
        0.03826904296875, 0.042236328125, 0.01300048828125, 0.103515625,
        0.058837890625, 0.1590576171875, 0.40179443359375, 0.1414794921875,
        0.02978515625, 0.01995849609375, 0.03680419921875, 0.0357666015625,
        0.004974365234375, 0.028961181640625, 0.03411865234375, 0.1917724609375,
        0.44940185546875, 0.191131591796875, 0.02618408203125, 0.01336669921875,
        0.03717041015625, 0.022918701171875, 0.0157470703125, 0.0946044921875,
        0.0870361328125, 0.16693115234375, 0.37554931640625, 0.1181640625,
        0.04400634765625, 0.01910400390625, 0.0379638671875, 0.0408935546875,
        0.011962890625, 0.1014404296875, 0.0570068359375, 0.1622314453125,
        0.40936279296875, 0.13818359375, 0.030029296875, 0.018798828125,
        0.03631591796875, 0.03466796875,
    ]
)


def test_reference_is_reproducible_from_notebook_port():
    """The committed golden is exactly what the notebook port yields on the
    frozen synthetic input — ties the constant to a reproducible source."""
    frames, landmarks = _synthetic_frames_and_landmarks()
    assert np.allclose(_nb_lbptop(frames, landmarks), NOTEBOOK_LBP_REFERENCE, atol=1e-12)


def test_lbp_top_matches_training_interpolation():
    """``lbp_top_features`` must reproduce the INTER_LINEAR (training) reference.

    FAILS if the ROI resize uses INTER_AREA (or any non-default filter): that
    shifts the 90-d block out of the trained feature space while still summing
    to 9.0, so only this value-level check catches it.
    """
    frames, landmarks = _synthetic_frames_and_landmarks()
    vec = F.lbp_top_features(frames, landmarks)
    assert vec.shape == (F.LBP_DIM,)
    assert np.allclose(vec, NOTEBOOK_LBP_REFERENCE, atol=1e-6)
